spring.application.name=Smart Health - Backend Service

# PostgreSQL Configuration (Render DB URL)
spring.datasource.url=jdbc:postgresql://smart-health-db-instance.c3kcc2misy4i.ap-southeast-1.rds.amazonaws.com:5432/initial_db
spring.datasource.username=postgres
spring.datasource.password=postgres!123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=DEBUG
logging.level.hibernate.resource=INFO
logging.level.org.hibernate.SQL=DEBUG
