spring.application.name=Smart Health - Backend Service

# Server Configuration
server.port=8080

# PostgreSQL Configuration (Render DB URL)
spring.datasource.url=postgresql://smart_health_9tae_user:GmFuYR5HB2kbowGPwD7UTZAXgwlxQkXF@dpg-cv1j86ogph6c73b5b9qg-a/smart_health_9tae
spring.datasource.username=smart_health_9tae_user
spring.datasource.password=GmFuYR5HB2kbowGPwD7UTZAXgwlxQkXF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true