spring.application.name=Smart Health - Backend Service

# PostgreSQL Configuration (Render DB URL)
spring.datasource.url=jdbc:postgresql://dpg-cvkctep5pdvs73ed8sig-a/smarth_health_db
spring.datasource.username=smarth_health_db_user
spring.datasource.password=vLQPNjYTuWjvUliS5wuXm5yx8cW6haaQ

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
