spring.application.name=Smart Health - Backend Service

# PostgreSQL Configuration (Render DB URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ethoslab!123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
